### ISSUE TITLE
Create/Update social login docs.

### ISSUE THREAD

**Issue by wpdev10** [AyeCode/uwp-social#17]
We have FB and Instagram social login setup doc available on doc site but they are now outdated so we need to update them and also create pages for other social logins LinkedIn, Google, Twitter, Yahoo, VKontakte, WordPress.

**Comment by wpdev10** [comment]
Can you please add the docs for Google asap? @sufyanism

**Comment by wpdev10** [comment]
Here are the steps for your reference:

1. Go to https://console.developers.google.com/
2. You will see dropdown after Google APIs logo click on it and then click Create Project link on the top right corner of the popup.
3. Fill in the details for the new project and click on create.
4. Again go to projects dropdown and select the project you created recently.
5. Click on ENABLE APIS AND SERVICES button and search for Google+ API and click on the enable button to enable that API.
6. After enabling click on the OAuth consent screen on the left sidebar menu and fill up all the details. Don't forget to enter your site URL into the Authorized domains.
7. After that, you will need to create credentials. Go to credentials on left sidebar menu. Click on Create credentials button and select OAuth client ID.
8. Choose Web application from the list and fill all the details. Enter the URL from the UsersWP google social login settings to the Authorized redirect URIs field and click on create.
9. You will get your Client ID and Client Secret in the popup. Enter those into our UWP google social login settings and you are done.

**Comment by sufyanism** [comment]
https://secure.helpscout.net/docs/5ea96cd52c7d3a5ea54a2151/category/5f8dac8fc9e77c00162191e2
