### ISSUE TITLE
Error on social login endpoint, when APP key and secret key are empty 

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/uwp-social#21]
<img width="1190" alt="Screenshot 2021-04-14 at 11 03 08 AM" src="https://user-images.githubusercontent.com/24760592/114660747-75ba1180-9d13-11eb-9907-56603bb67726.png">

**Comment by wpdev10** [comment]
@1naveengiri If the App key and secrets are not added from the settings then the social login icons should not be displayed on the form. Do you see them or how to reproduce this issue so we can fix?

**Comment by 1naveengiri** [comment]
Okey, I see. 
so we will have to fix it another way. 
steps to reproduce the issue. 

Keep APP ID and key empty and visit Authorized redirect URI. 

http://ppldb.com/naveen/wp-admin/admin.php?page=userswp&tab=uwp-social&section=google
example http://ppldb.com/naveen/uwphauth/google

**Comment by wpdev10** [comment]
Bro the authorized redirect URI is for adding on to the App settings in google console and not for direct access. We might restrict direct access either by showing an error message or redirecting to the 404 page.

**Comment by wpdev10** [comment]
Are you trying to access the URL directly? If you check http://ppldb.com/uwp/uwphauth/google/ it gives a 404 page not found error and the same should happen on your site. Not sure why it's throwing an error.

**Comment by 1naveengiri** [comment]
@wpdev10 I notice this issue when I access that Auth URL after saving the social login from without Keys.

**Comment by wpdev10** [comment]
Means you are accessing the URL directly right? It's for adding on the social site app configuration and not for using directly. Even one uses it directly then will go to the 404 page. If no action needed then you can close the issue.

**Comment by 1naveengiri** [comment]
<img width="1023" alt="Screenshot 2021-04-15 at 4 24 15 PM" src="https://user-images.githubusercontent.com/24760592/114858428-12a9a700-9e07-11eb-9a85-7a0554063015.png">

Since URL is mentioned in the backend. It could be possible user want to check it directly. 
redirecting on the 404 page is a perfect solution. 

but it should not throw Fatal error in any case. I will close it after the last confirmation.

**Comment by wpdev10** [comment]
We have mentioned the text that the admin has to use this URL in the app and even it's not clickable. Also, we have not received such a request till now from any of our customers so there is no point of looking more into this. I have made one change to check if there is a session set and if not then it will return as the session will be set when one does follow the social login process and not directly access the URL.
